### ISSUE TITLE
Feature: Partial Grades (Teilleistungen)

### ISSUE THREAD

**Issue by urvdp** [spz-signup/spz-signup-app#31]
## Description:
In Spanish and English courses, teachers can give partial grades that determine, together with the exam result, the final grade. It is important for the course admins (Fachleiter) to know how the final grade is made up.

## ToDo:
- [x] upload function on teacher view
- [x] error checking to validate for valid grade template
- [x] read in final grade
- [x] internal storing of the file with a unique name in the docker container
- [x] view for admins: possibility to download/see uploaded course file
- [ ] (backup: easy download option for all files)
